### PR TITLE
Adding nix flake

### PR DESCRIPTION
**Pull request by TornaxO7**

### CODE REVIEW

**Comment by ModProg** [comment]
Could you maybe add a sentence on how to install/run with nix.

**Comment by TornaxO7** [comment]
> Could you maybe add a sentence on how to install/run with nix.

hm... do you mean in the README? Hm... I'm unsure if it's worth it. But if you want, I can add a section.

**Comment by ModProg** [comment]
If it'd be more complex than the sentence I put for `cargo install` feel free to leave it be. I guess nix users would know, and others would better look into the nix docs directly.

**Comment by TornaxO7** [comment]
> If it'd be more complex than the sentence I put for `cargo install` feel free to leave it be. I guess nix users would know, and others would better look into the nix docs directly.

Well, there are different ways to execute your program but luckily there are multiple ways to achieve this. I'll add a small section into the README this evening.

**Comment by TornaxO7** [comment]
sorry for the late reply, I added a little section for it.

**Pull request merged**
